### ISSUE TITLE
Version 2.3.5 seems to have much increased processor use

### ISSUE THREAD

**Issue by HG943** [lavinir/hassio-onedrive-backup#254] opened 2024-11-22 08:45 UTC
After installing 2.3.5, my average CPU load increased from 2% to 4% (yes, may sound low overall, but is actually a 100% increase due to a single add-on).
Zooming in on the graphs, it seems some task is now using 10% CPU load every 5 minutes. This increase coincided with the install of 2.3.5, so would be great if you could take a look at it.

![CPU load](https://github.com/user-attachments/assets/a1886910-8a77-46e7-a9d9-21c064cc44a3)
![zoom](https://github.com/user-attachments/assets/b1d4d60b-a373-4320-bec6-07f732c765be)

**Comment by lloyda** [comment] 2024-11-23 19:23
I've seen the same, and the increase in processor usage makes HA too sluggish - I've had to disable the add in.

**Comment by spmaid** [comment] 2024-11-24 14:49
I too have had to disable the latest update, first notice the CPU running hotter, then loads of sections not loading, or rarther, taking a very long time, suspected my HA install was corrupt, then recalled that I had installed the latest update, or rather, re-linked to OneDrive after it had updated a few days prior.  Rebooting to safe mode made no difference.  Eventually managed to get in to the add on to stop, took a very long time to both get to the add on page, then the OneDrive add on, then for it to stop.  All is now well with HA now I have stopped the add on.  Here is the difference it has made to the CPU temp now I've disabled. 

<img width="561" alt="image" src="https://github.com/user-attachments/assets/8e50e071-1239-415a-9733-434d695c4de1">

**Comment by lavinir** [comment] 2024-11-24 15:27
Did you look for errors in the logs as well? There are a lot of people experiencing these issues of upload failures that I want to rule out as the cause first. I'm working on an update for this first. Once that's resolved if there is still increased CPU usage I will take a look at it.

**Comment by HG943** [comment] 2024-11-24 19:26
Yes, seems to be upload issues in the log. For now I have the addon disabled. Will try it again when there's an update.

Great addon by the way, been using it for a while !

**Comment by spmaid** [comment] 2024-11-24 21:17
> Did you look for errors in the logs as well? There are a lot of people experiencing these issues of upload failures that I want to rule out as the cause first. I'm working on an update for this first. Once that's resolved if there is still increased CPU usage I will take a look at it.

I did try looking in some logs, but there were a lot of different errors for loads of other things not working and not sure I was checking the correct logs as I download the full logs though whilst it was working, but having taken a look, it doesn't give any extra clues and is just full of errors for everything else in HA that was not loading at the time.

**Comment by lavinir** [comment] 2024-11-25 08:37
Please try to update to 2.3.6 and update if you're still seeing issues.

**Comment by spmaid** [comment] 2024-11-25 11:48
> Please try to update to 2.3.6 and update if you're still seeing issues.

Updated, backup triggered, and uploading now and CPU temp on the way back down post backup, so, so far so good! 

<img width="561" alt="image" src="https://github.com/user-attachments/assets/ab50703f-7483-4718-ab2f-06b41e6a5125">

**Comment by HG943** [comment] 2024-11-25 12:15
Been running for about an hour now and so far looking good.
Will update if I see something strange, but seems you fixed the issue.
 
Thanks!

**Comment by lavinir** [comment] 2024-11-26 12:22
Thanks, Closing for now.

**Closed by lavinir** 2024-11-26 12:22 UTC
