### ISSUE TITLE
Sync interval every 5 minutes

### ISSUE THREAD

**Issue by leroyloren** [lavinir/hassio-onedrive-backup#22] opened 2022-12-02 19:18 UTC
Hi, is the sync check interval intended to be every 5 minutes?

If so, would it be possible to turn this off and use the add-on only for backups at a given time?

Personally, it is enough for me to create/upload a backup at the given time and it is not necessary to check something every 5 minutes (outside the set time).

![obrazek](https://user-images.githubusercontent.com/57643470/205368956-6c2f1a1f-5ba4-4ccc-aa5c-c0b8792ca546.png)

**Comment by lavinir** [comment] 2022-12-02 21:00
Hi, yes this is by design. It does minimal checks though at these intervals only doing work if necessary. 
There are possible issues that can occur with having this wake up at higher intervals or only during set backups time:
* Potential starvation when setting specific allowed hours for the backups
* Failed / Missed backup - You wouldn't want to wait for the next backup iteration to attempt this. 
* Stale Sensor data - As the sensor is only updated each run interval.

What's the concern with having this done every 5 minutes ? Even if you are certain you don't *need* this what's the downside of having a few seconds of runtime every 5 minutes ?

**Comment by leroyloren** [comment] 2022-12-02 21:37
Thanks for the explanation.

> What's the concern with having this done every 5 minutes ? Even if you are certain you don't _need_ this what's the downside of having a few seconds of runtime every 5 minutes ?

A minimum of unnecessary records in the logbook, and moreover quite often. If something is going to happen in the background, let it happen, but it is not necessary to expose it to the sensor.

The current state is that 600 records/day are created, completely unnecessary in my opinion.

**Comment by lavinir** [comment] 2022-12-03 13:12
Ok I understand the ask now. I'll amend the "Syncing" updates in the next update.

**Comment by lavinir** [comment] 2022-12-06 20:42
1..22 is released. Closing issue.

**Closed by lavinir** 2022-12-06 20:42 UTC
Labels: 1.22
